FROM python:3.11-alpine
WORKDIR /app

RUN apk add bind git rustc-dev cargo openssl-dev pkgconf bash
COPY bind/named.conf.local /etc/bind/named.conf.local
COPY bind/zones/ /var/lib/bind/pri/
RUN chown named -R /var/lib/bind/pri/
RUN git config --global --add safe.directory /app
RUN --mount=type=bind,source=./pyproject.toml,target=/app/pyproject.toml cd /app && pip install --upgrade pip && pip install -e . && pip install -r requirements.d/dev.txt

CMD ["/app/scripts/docker/test.sh"]
