# Generated by Django 4.2.29 on 2026-03-28 13:15

import django.core.validators
from django.db import migrations, models
import nsupdate.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_blacklistedhost_name_re_alter_domain_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='nameserver2_port',
            field=nsupdate.main.models.RangeIntegerField(default=53, help_text='Port to use', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='nameserver port to use (secondary)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver2_protocol',
            field=models.CharField(choices=[('tcp', 'tcp'), ('udp', 'udp')], default='tcp', help_text='Protocol to use', max_length=4, verbose_name='nameserver protocol (secondary)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver_port',
            field=nsupdate.main.models.RangeIntegerField(default=53, help_text='Port to use', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='nameserver port to use (primary)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver_protocol',
            field=models.CharField(choices=[('tcp', 'tcp'), ('udp', 'udp')], default='tcp', help_text='Protocol to use', max_length=4, verbose_name='nameserver protocol (primary)'),
        ),
    ]
