# Generated by Django 4.2.29 on 2026-03-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_domain_nameserver2_port_domain_nameserver2_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='nameserver_update_key_name',
            field=models.CharField(default='', help_text='Name of the key as it exists in bind.conf . Must be the same as it is in the bind configuration.', max_length=128, verbose_name='nameserver update secret'),
        ),
    ]
