# Generated by Django 5.2.13 on 2026-05-21 18:47

import django.core.validators
import nsupdate.main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_domain_nameserver_update_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceupdater',
            name='port',
            field=nsupdate.main.models.RangeIntegerField(default=443, help_text='Port to use - default is 80 for http and 443 for https', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Update Server http(s) port to use'),
        ),
    ]
